services:
  backend:
    build:
      context: ./
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://postgres:test123@mydb:5432
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
  db:
    image: postgres:15
    container_name: postgress_container
    restart: always
    environment:
      POSTGRESS_USER: postgres
      POSTGRESS_PASSWORD: test123
      POSTGRESS_DB: mydb
    ports:
      - "5432:5432"
